<a href="https://colab.research.google.com/github/tharushi621/Kaggle-Works/blob/main/Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [3]:
df=pd.read_csv('tested.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
df.drop(['Name','PassengerId','SibSp','Parch','Ticket','Cabin','Embarked','Fare'],axis='columns',inplace=True )
df.head()

   Survived  Pclass     Sex   Age
0         0       3    male  34.5
1         1       3  female  47.0
2         0       2    male  62.0
3         0       3    male  27.0
4         1       3  female  22.0

In [7]:
iv=df.drop('Survived',axis='columns')
dv=df.Survived

In [9]:
iv

     Pclass     Sex   Age
0         3    male  34.5
1         3  female  47.0
2         2    male  62.0
3         3    male  27.0
4         3  female  22.0
..      ...     ...   ...
413       3    male   NaN
414       1  female  39.0
415       3    male  38.5
416       3    male   NaN
417       3    male   NaN

[418 rows x 3 columns]

In [10]:
dv

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [11]:
dummies=pd.get_dummies(iv.Sex,dtype=int)

In [12]:
dummies.head(200)

     female  male
0         0     1
1         1     0
2         0     1
3         0     1
4         1     0
..      ...   ...
195       0     1
196       0     1
197       1     0
198       0     1
199       1     0

[200 rows x 2 columns]

In [13]:
iv=pd.concat([iv,dummies],axis='columns')

In [14]:
iv.head(3)

   Pclass     Sex   Age  female  male
0       3    male  34.5       0     1
1       3  female  47.0       1     0
2       2    male  62.0       0     1

In [15]:
iv.drop(['Sex','male'],axis='columns',inplace=True)

In [16]:
iv.head(3)

   Pclass   Age  female
0       3  34.5       0
1       3  47.0       1
2       2  62.0       0

In [17]:
iv.columns[iv.isna().any()]

Index(['Age'], dtype='object')

In [18]:
median_age=math.floor(df.Age.median())
print(median_age)

27

In [19]:
iv['Age'].fillna(value=median_age,inplace=True)

/tmp/ipykernel_1602/310242868.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iv['Age'].fillna(value=median_age,inplace=True)

In [20]:
iv.head(3)

   Pclass   Age  female
0       3  34.5       0
1       3  47.0       1
2       2  62.0       0

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,Y_train,Y_test=train_test_split(iv,dv,test_size=0.3)

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
model=GaussianNB()

In [25]:
model.fit(X_train,Y_train)

GaussianNB()

In [26]:
model.score(X_test,Y_test)

1.0

In [28]:
X_test[0:10]

     Pclass   Age  female
309       3  45.0       1
302       2  43.0       0
270       1  46.0       0
383       3  19.0       1
2         2  62.0       0
153       3  36.0       1
77        1  55.0       1
355       1  50.0       0
14        1  47.0       1
329       2  21.0       0

In [29]:
Y_test[0:10]

309    1
302    0
270    0
383    1
2      0
153    1
77     1
355    0
14     1
329    0
Name: Survived, dtype: int64

In [30]:
model.predict(X_test[0:10])

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [31]:
Y_test[0:10]

309    1
302    0
270    0
383    1
2      0
153    1
77     1
355    0
14     1
329    0
Name: Survived, dtype: int64